### ISSUE TITLE
$page.path has been replaced by $page.url.pathname

### ISSUE THREAD

**Issue by tnedich** [mylastore/svelte-kit#3]
This error appears, 
I have changed code with suggested and some of it works.

This is what I can not figure (I am just amateur coder)

`start.js:841 
Uncaught (in promise) Error: $page.path has been replaced by $page.url.pathname
    at Object.get (start.js:841)
    at [p].svelte? [sm]:59
    at start.js:416
    at Object.subscribe2 [as subscribe] (index.mjs:50)
    at Object.subscribe (start.js:414)
    at Object.subscribe (stores.js:47)
    at instance ([p].svelte? [sm]:59)
    at init (index.mjs:1809)
    at new U5Bpu5D ([p].svelte? [sm]:66)
    at createProxiedComponent (svelte-hooks.js:266)`

**Comment by PhiltasticGuy** [comment]
Hi @tnedich, I just ran into the same error. You can run a search/replace in the file `src/lib/Nav.svelte` to replace `$page.path` by `$page.url.pathname`. This worked for me.

Good luck!

**Comment by mylastore** [comment]
Thanks, I will check out.

**Comment by tnedich** [comment]
> Hi @tnedich, I just ran into the same error. You can run a search/replace in the file `src/lib/Nav.svelte` to replace `$page.path` by `$page.url.pathname`. This worked for me.
> 
> Good luck!

Yes, I have done that but than still encountered this error. 
**WIN10, 64-bit**
**node --version v14.17.4**

**Comment by mylastore** [comment]
Updated dependencies to the latest, updated all instances of the $page.path to $page.url.pathname also corrected getting all the users function.
